### ISSUE TITLE
Support for the Type() function in PICO-8?

### ISSUE THREAD

**Issue by Liquidream** [dansanderson/picotool#20]
Hi,

It seems that luamin does not recognise the Type() function in PICO-8?

I use this function quite a lot and in the minified output, it seems to leave renamed function calls (e.g. **ab()** ), but there's never a definition of what **ab** is?

Let me know if you need any further information (or can't replicate!)

Thanks

**Comment by dansanderson** [comment]
Accepted. The fix is to add b'type' to this list: https://github.com/dansanderson/picotool/blob/master/pico8/lua/lexer.py#L24

**Comment by Liquidream** [comment]
Thanks for the suggested workaround.

Unfortunately, adding this appears produces the following error when I next run **luamin**:
`exp2 in binop at line 104 char 12`

However, changing `b'type'` to `b'foo'` appears to be fine.  So perhaps it's something about the word "type" that's the problem?

Hope this helps. 😃

**Comment by dansanderson** [comment]
In that case add it to: https://github.com/dansanderson/picotool/blob/master/pico8/lua/lua.py#L24

I think that other list expects the Lua parser to handle the keyword as part of the grammar. The Pico-8 builtins list are just used as reserved function and variable names that should not be minified. So even though type() is a Lua feature it's best thought of as a builtin. (Maybe a separate list of "Lua builtins" is called for.)

**Comment by Liquidream** [comment]
Yup, that did the trick! :smile:  Thanks.

So... do you think this "separate list" idea would also be a solution to having a "do_not_minify" list (mentioned in [another issue](https://github.com/dansanderson/picotool/issues/14))?

You talked about using "externs" for that - so sounds like you were planning a diff/better way to implement?

**Comment by dansanderson** [comment]
Added type() to the core built-in list for luamin.
