### ISSUE TITLE
Multiple lua files

### ISSUE THREAD

**Issue by fmahnke** [dansanderson/picotool#22]
Is assembling a cart from multiple lua files supported?

My use case is to separate my reusable code into multiple .lua files, then bring the library code for my different systems into the cart file.

**Comment by jessemillar** [comment]
Based on my reading of the README file for picotool, there isn't support for multiple .lua files. [My tool](https://github.com/jessemillar/pico-build) definitely supports multiple .p8 files though for anyone else that wants a bit more code organization like I did.

**Comment by fmahnke** [comment]
Thanks! My current solution is to cat the different .lua files together, then use picotool as usual.

This can cause strange errors if I'm not careful, so I'll eventually want something more robust. I'll check out yours.

**Comment by dansanderson** [comment]
It's easy enough to script simple concatenation with picotool, which sounds like what you're already doing:

```
cat s1.lua s2.lua s3.lua >/tmp/cat.lua
p8tool build --lua /tmp/cat.lua mycart.p8.png
```

I have plans for a more robust version of this, but they're elaborate enough plans that I haven't finished it yet. :)

**Comment by dansanderson** [comment]
`p8tool build --lua source.lua` now supports `source.lua` containing a `require()` statement it in, with elaborate support for that. That'll be the built-in support for multiple Lua files. You can still script your own concatenation method as above, if that's preferred.

**Comment by jessemillar** [comment]
@dansanderson That sounds awesome and much more robust than my concatenation method.
