### ISSUE TITLE
Allow config for only renaming vars and stripping comments

### ISSUE THREAD

**Issue by morningtoast** [dansanderson/picotool#26]
I'm not exactly sure what all the "luamin" options does entirely, but I'm really needing it just rename variables and strip out comments.

When I run the tool and it compresses, I get a lot of one-off-ish errors when I try to run, like a problem with a equal sign or something. Opening the cart, it looks like it might be something with the whitespace compression moving things next to each other...when I add whitespace it sometimes works. Sorry I can't provide more detail then that.

But just having the ability to tell p8tool to rename variables and leaving everything else the same would do wonders on saving compression size. 

Thanks for your work thus far. the p8tool works great in most cases...just came across one cart I'm making where the output gives pico-8 some grief.

**Comment by dansanderson** [comment]
I just fixed an issue with short-ifs that might be all you need. luamin now preserves all newlines, and truncates/condenses other whitespace.

I'm going to resolve this issue for now, but please re-open (or open a new one) if you notice luamin breaking anything with regards to whitespace. I can also see potential use of a "preserve whitespace" feature for luamin, so let me know if that's something you'd want.
