### ISSUE TITLE
Broken for latest version

### ISSUE THREAD

**Issue by pakoito** [dansanderson/picotool#3]
Version: pico-8_0.1.6

Cartridge: http://www.lexaloffle.com/bbs/?tid=3191

```
$ python p8tool stats ..\Cartridges\19598.p8.png

..\Cartridges\19598.p8.png: Syntax error (remaining:'! /* a lot of unformatted Lua code here */ ') at line 566 char 16

..\Cartridges\19598.p8.png: could not load cart
```

**Comment by dansanderson** [comment]
The linked cart no longer matches the error report, so I can't say for sure what happened. I just submitted a few improvements to support and catch more cases, including multi-line comments if that was the issue. (Multi-line strings are still to-do.)

Let me know if you can still reproduce the issue. Thanks!

**Comment by pakoito** [comment]
Many thanks!
