### ISSUE TITLE
Support "?" short-print statements

### ISSUE THREAD

**Issue by dansanderson** [dansanderson/picotool#39]
Pico-8 has another preprocessor macro that treats

```
? x,y,z
```

as

```
print(x,y,z)
```

As with short-if, this requires that the statement be on its own line. Short-print is mostly intended for use at the command prompt, but some carts use it in cart code because it's one token shorter than print with parens, and fewer chars.

For completeness, maybe Picotool should attempt to support this. I probably wouldn't want to do this unless I remove short-if from the grammar and more properly treat both macros as actual preprocessing steps--taking extra care to flag the AST so it dumps the original short-form statement.

**Comment by hsandt** [comment]
So is https://github.com/dansanderson/picotool/commit/e4b402c9b135a92db24734aa5339718cc9482d77 fixing it?

**Comment by dansanderson** [comment]
Looks like it. :) Let me know if it doesn't.
