### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by rickomax** [dansanderson/picotool#49]
Seems PicoTool is not accepting the emoji-like symbols Pico-8 files uses:

> C:\Users\ricko\AppData\Roaming\pico-8\carts>python XXX\p8tool luafmt test.p8
test.p8: Syntax error (remaining:b'\xf0\x9f\x85\xbe\xef\xb8\x8f,0)) then\n') at line 636 char 30

**Comment by rickomax** [comment]
Related to #36

**Comment by Liquidream** [comment]
Yup, having the same issue when trying to use luamin with code like:
``` 
if(btn(⬆️)) ship.thrust+=acc
if(btn(⬇️)) ship.thrust-=acc 
```

**Comment by Feneric** [comment]
You may want to try the version in [my pull request](https://github.com/dansanderson/picotool/pull/54). It should handle the escaped version of the characters fine.

**Comment by dansanderson** [comment]
I believe this is the same as #36 so I'm resolving as a dupe. There's a potential solution in a pending PR that I hope to fold in soon.
