### ISSUE TITLE
Missing some of the newer builtins

### ISSUE THREAD

**Issue by Liquidream** [dansanderson/picotool#57]
Hi,
The PICO8_BUILTINS list is missing a few more recent functions 
(and therefore, incorrectly minifying them):
- b'**time**',
- b'**t**', 
- b'**lshr**', 
- b'**rotr**', 
- b'**rotl**', 
- b'**ceil**'

I was about to create a PR, but can see there's already one (#54) still open that seems to cover these and more?

**Comment by Liquidream** [comment]
Hi @dansanderson,
Just wondering if these built-ins (and others, like single-line IF's and other common PICO-8 shortcuts) have been integrated to `luamin` yet.
(Coz it doesn't seem so, and I see the linked PR #54 is still open...) 🤔

**Comment by dansanderson** [comment]
Hi @Liquidream, sorry I haven't merged in Feneric's contributions yet, I need to get to it. It's on my radar, I promise. :)

**Comment by dansanderson** [comment]
Resolved in 3b43f3c8e8d9ec7c06b761d39c9df71566588d71. Thanks for your patience! :)
