### ISSUE TITLE
luamin doesn't understand t()

### ISSUE THREAD

**Issue by MagnusRunesson** [dansanderson/picotool#63]
luamin doesn't understand that t() is a built-in method in Pico8 and replace it with a "random" function call.

This code:
```
function _update60()
	t()
end
```

minifies to:
```
function _update60()
	a()
end
```

resulting in a:
`attempting to call global 'a' (a nil value)`

**Comment by dansanderson** [comment]
Resolved in 3b43f3c8e8d9ec7c06b761d39c9df71566588d71
