### ISSUE TITLE
`..=` token crashes picotool.py

### ISSUE THREAD

**Issue by Lambdanaut** [dansanderson/picotool#69]
The stats command crashes if the code contains any `..=` tokens. 

The error in question:

```
python p8tool stats pico.p8
../picofile.p8: Expected b'end' at line 1010 char 21
../picofile.p8: could not load cart
```

These tokens can be very useful because they can reduce a token count by one. 

For instance:

> x = x .. string

becomes

> x ..= string

Super great, but at the moment we can't use them with this tool.

**Comment by dansanderson** [comment]
Fixed in 9dfeb7985fee045ecd4af337f4fa31fea59830af.
