### ISSUE TITLE
New Integer division operator "\" causes syntax error

### ISSUE THREAD

**Issue by Liquidream** [dansanderson/picotool#71]
The new integer division "**\**" operator, introduced in PICO-8 v0.2 fails with the following syntax error:
```
Syntax error (remaining:b'\\8\n') at line 292 char 15
```

Not too surprising, as it is probably treating it as an escape char.

Trouble is, this new command is useful for saving tokens (and avoids the need for `flr()`) - but alas, I cannot use this (and other new API features) as luamin/picotool is, sadly, quite out of date.

If I knew how to resolve this myself in python - I'd have a stab, but I do not
(also, there are a number of PR's still open, so I wouldn't wanna add to the pile for now 😉 )

**Comment by dansanderson** [comment]
I added the newer binary operators in 54b84fe74b95c98a562822b2c42f6b3e9f4c0690.
